### ISSUE TITLE
Adding options

### ISSUE THREAD

**Issue by ghost** [wtsnz/Triangle#2]
Thank you very much for your work, I managed to make it work into an app I'm trying to make (I am not a developper but a scientist). To me, the great strength of Triangle as compared to other available Delaunay triangulations is the possibility for conforming triangulation and for that, having the options for area is a must have. As you said you were inspired by the golang port, I was wondering if you could make such options available as they did?

// NewOptions returns a new options struct with default parameters
func NewOptions() *options {
	return &options{ConformingDelaunay: true, EncloseConvexHull: false,
		SegmentSplitting: SplittingAllowed, Area: 15.0, Angle: 20.0,
		MaxSteinerPoints: -1}
}

Best, Guillaume

**Comment by gverez** [comment]
Alright, I found the solution to my problem, sorry for the inconvenience.

To anyone who want to use more detailed options than specified, you can have a look into the file Triangulate.swift, and change the line:
"let arguments = CString("QzpD")" or another Cstring argument being used. The idea is just to add more options in this string, which are nothing more than those given in this list: https://www.cs.cmu.edu/~quake/triangle.switch.html

So for me, having a constraint on the angle resumed to right:
let arguments = CString("QzpDq20.0")

So thank you again for your great work!
